Repository codewithhermes/Job-Searching-Web-App, pull requests merged in 2024-10, with the labels that each got.

#4 Adding job feature in JobRestController.java
  Job Searching Portal/src/java/JobRestController.java
Labels: hacktoberfest, hacktoberfest-accepted

#9 Update JobRestController.java
  Job Searching Portal/src/java/JobRestController.java
Labels: hacktoberfest, springboot, hacktoberfest-accepted

#10 Added Lombok Dependency
  Job Searching Portal/pom.xml
  Job Searching Portal/src/java/JobPost.java
Labels: hacktoberfest, backend, hacktoberfest-accepted

#11 Update JobRestController.java
  Job Searching Portal/src/java/JobRestController.java
Labels: hacktoberfest, hacktoberfest-accepted

#14 Update JobRestController.java
  Job Searching Portal/src/java/JobRestController.java
Labels: hacktoberfest, hacktoberfest-accepted

#12 Update JobService.java
  Job Searching Portal/src/java/JobService.java
Labels: hacktoberfest, hacktoberfest-accepted

#18 Job add Feature
  Job Searching Portal/src/java/JobRestController.java
  Job Searching Portal/src/java/JobService.java
Labels: hacktoberfest, backend, hacktoberfest-accepted

#19 Update JobRestController.java
  Job Searching Portal/src/java/JobRestController.java
Labels: hacktoberfest, backend, hacktoberfest-accepted
